services:
  - type: worker
    name: telegram-cash-bot
    plan: free
    envVars:
      TOKEN: 8467867383:AAGrCYHbRJqxZwPm2rS8YCjb5Wf_ulLVG_o
    buildCommand: docker build -t bot .
    startCommand: docker run bot
