services:
  - type: worker
    name: telegram-cash-bot
    runtime: python
    envVars:
      PYTHON_VERSION: 3.11.9
    buildCommand: |
      python -m venv venv
      . venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      . venv/bin/activate
      python app.py
    plan: free

