services:
  - type: worker
    name: telegram-cash-bot
    runtime: python
    buildCommand: |
      python3 -m venv venv
      . venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      . venv/bin/activate
      python app.py
    plan: free
